"""add password hash to students

Revision ID: 9ffccd3f23f5
Revises: b9149bb383de
Create Date: 2026-09-26 13:54:50.633602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ffccd3f23f5'
down_revision: Union[str, Sequence[str], None] = 'b9149bb383de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'password_hash')
    # ### end Alembic commands ###
