"""create students table

Revision ID: b9149bb383de
Revises: 
Create Date: 2026-09-26 13:49:32.139341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9149bb383de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', name='student_status'), nullable=False),
    sa.Column('created_ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('created_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('updated_ip_address', postgresql.INET(), nullable=True),
    sa.Column('updated_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('updated_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_ip_address', postgresql.INET(), nullable=True),
    sa.Column('deleted_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('deleted_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
