"""create enrollment_batches table

Revision ID: 1ea4b579e508
Revises: 768c88691e54
Create Date: 2026-09-30 12:33:43.722872
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1ea4b579e508'
down_revision: Union[str, Sequence[str], None] = '768c88691e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_batches',
    sa.Column('enrollment_batch_id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.enrollment_id'], ),
    sa.PrimaryKeyConstraint('enrollment_batch_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment_batches')
    # ### end Alembic commands ###
