"""create batches table

Revision ID: 768c88691e54
Revises: 97139a701ba2
Create Date: 2026-09-30 12:28:46.325667
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '768c88691e54'
down_revision: Union[str, Sequence[str], None] = '97139a701ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='batch_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batches')
    # ### end Alembic commands ###
