"""create enrollments table

Revision ID: 97139a701ba2
Revises: 4ca69f8b395c
Create Date: 2026-09-30 12:24:35.921436
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '97139a701ba2'
down_revision: Union[str, Sequence[str], None] = '4ca69f8b395c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='enrollment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollments')
    # ### end Alembic commands ###
